{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.1.jar",
          "url": "spring-tx-6.2.1.jar",
          "size": 284918,
          "sha512": "751cff1218a362464c70aadba9fc62a69d8a97e7b5ebfec833c6c415336985dee33fe81a80705aa336be9b6b1c8486083d779fcea41136f692098d43b4a3a3f4",
          "sha256": "388ca8b88a8a8e252973a1491e5de5b85b909cc16e5ac6aa426174f161c23b93",
          "sha1": "5ffde4fee85ff021ad613b9e86a9be893fb52572",
          "md5": "d38c8016465af5167f9c1a250889a179"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.1.jar",
          "url": "spring-tx-6.2.1.jar",
          "size": 284918,
          "sha512": "751cff1218a362464c70aadba9fc62a69d8a97e7b5ebfec833c6c415336985dee33fe81a80705aa336be9b6b1c8486083d779fcea41136f692098d43b4a3a3f4",
          "sha256": "388ca8b88a8a8e252973a1491e5de5b85b909cc16e5ac6aa426174f161c23b93",
          "sha1": "5ffde4fee85ff021ad613b9e86a9be893fb52572",
          "md5": "d38c8016465af5167f9c1a250889a179"
        }
      ]
    }
  ]
}
