{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.1.jar",
          "url": "spring-boot-starter-logging-3.4.1.jar",
          "size": 4760,
          "sha512": "56f6235ec1cd2c504272b1c8536992c7569e32e762756bf0f30bb7b042705bc25e7c109ef89fe93255bdb267fa771cbd9d692c8d0a54af43d6acc5c09e83b792",
          "sha256": "3a2b5aa454fa876e08273c8437d340aa24518f774e1c2f2bf8b5970259f2e604",
          "sha1": "5cd01e208b15113c7f88b3ea40e843ea9989f38a",
          "md5": "aff6dc47456162415ad41396be9904bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.1.jar",
          "url": "spring-boot-starter-logging-3.4.1.jar",
          "size": 4760,
          "sha512": "56f6235ec1cd2c504272b1c8536992c7569e32e762756bf0f30bb7b042705bc25e7c109ef89fe93255bdb267fa771cbd9d692c8d0a54af43d6acc5c09e83b792",
          "sha256": "3a2b5aa454fa876e08273c8437d340aa24518f774e1c2f2bf8b5970259f2e604",
          "sha1": "5cd01e208b15113c7f88b3ea40e843ea9989f38a",
          "md5": "aff6dc47456162415ad41396be9904bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-logging-3.4.1-javadoc.jar",
          "size": 4760,
          "sha512": "562a18d9e54bf15dba873271e79078db89474ead79428336405e7413f34592dd4744e2bf8e5d5c4323b18dbb957b5b1a6786a1af8c53fd0bab6791208540e009",
          "sha256": "2056743c8f9711d38887663d56dbc8dc9bf4c83d40e7cbc42da6e3a0ba428f57",
          "sha1": "f54568fb12b210bc13cf1d6cea2347551cc9082e",
          "md5": "8b03341642d31f4d274f31183f38a990"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.1-sources.jar",
          "url": "spring-boot-starter-logging-3.4.1-sources.jar",
          "size": 4760,
          "sha512": "562a18d9e54bf15dba873271e79078db89474ead79428336405e7413f34592dd4744e2bf8e5d5c4323b18dbb957b5b1a6786a1af8c53fd0bab6791208540e009",
          "sha256": "2056743c8f9711d38887663d56dbc8dc9bf4c83d40e7cbc42da6e3a0ba428f57",
          "sha1": "f54568fb12b210bc13cf1d6cea2347551cc9082e",
          "md5": "8b03341642d31f4d274f31183f38a990"
        }
      ]
    }
  ]
}
