[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["./gradlew bootJar --no-daemon -x test"]

[start]
cmd = "java -Dspring.profiles.active=default -Dspring.autoconfigure.exclude=com.google.cloud.spring.autoconfigure.sql.GcpCloudSqlAutoConfiguration -jar build/libs/*.jar"