{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.1.jar",
          "url": "spring-boot-gradle-plugin-3.4.1.jar",
          "size": 146171,
          "sha512": "de6ab836aaed5b0a971cecf81ec0c65a8aa69cc5b16d13703e73fc262dd2aad2306ddd262c68a6ad2bc7237eaf452200fcb0fc7b5052457b4372b3fab2e024ef",
          "sha256": "c71016ab7458fbd5bab8f082ce534e2c4f8e1637b4124a562a13a023d3b27dbd",
          "sha1": "7e3b9735dd3c38d9538fd730e5adf32aeb6b316f",
          "md5": "1a5f66ea15ae64d39824c18d2f19470f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.1.jar",
          "url": "spring-boot-gradle-plugin-3.4.1.jar",
          "size": 146171,
          "sha512": "de6ab836aaed5b0a971cecf81ec0c65a8aa69cc5b16d13703e73fc262dd2aad2306ddd262c68a6ad2bc7237eaf452200fcb0fc7b5052457b4372b3fab2e024ef",
          "sha256": "c71016ab7458fbd5bab8f082ce534e2c4f8e1637b4124a562a13a023d3b27dbd",
          "sha1": "7e3b9735dd3c38d9538fd730e5adf32aeb6b316f",
          "md5": "1a5f66ea15ae64d39824c18d2f19470f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.1-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.4.1-javadoc.jar",
          "size": 323037,
          "sha512": "13e0d63503c109211162fb1627d27ce53e6174550a869abf13e34d2f061ac099a783a33da8ef343e3b2dd5b972c72b7dcb78356d31937ad3062377514463408d",
          "sha256": "fcdb1c2ad0e0c12557ad7d844eccca87dc9652ff444a1e0a4718074978673d9b",
          "sha1": "8858a61f486c9b306eea9b24d0029d252d43b668",
          "md5": "fbfde336ed648ac36f1256f83f0b98d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.1-sources.jar",
          "url": "spring-boot-gradle-plugin-3.4.1-sources.jar",
          "size": 83395,
          "sha512": "7ea1197aa397ae9ffb9c97c601b9fe4b77125bae4f0b394925a5c87981191508ef3e878d0c2b5860346c3a8c57976b71c6243d8f14bec6e6c7ccef42168cafec",
          "sha256": "ea7cabae837eca6deb8666e857435e2f2df4d1c8036fc6ccff2a6c82854bbff0",
          "sha1": "907577f8168978bec587e3919bd57929ba5254d8",
          "md5": "7fd3232460a0b8fb64f84d5544410ec4"
        }
      ]
    }
  ]
}
