{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.1.jar",
          "url": "spring-aop-6.2.1.jar",
          "size": 418404,
          "sha512": "b5e2122fcbbea44afbd0226a9b2a84a825c5c2e6e850ea7d9754636f6a8afca3df7459c1c3e284bce167b6cd71c5143aa75943c6d3de8b76dd1a7357f9916a2c",
          "sha256": "a9cb0dddec1312c1cc6bc6a1762ad880f0e8b2a82ea2243b91abf2ac9debb86b",
          "sha1": "a9384de38fc00751084446ba014a0c4962240244",
          "md5": "ebfcdfe96624e5a3de3d0d6522c8593a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.1.jar",
          "url": "spring-aop-6.2.1.jar",
          "size": 418404,
          "sha512": "b5e2122fcbbea44afbd0226a9b2a84a825c5c2e6e850ea7d9754636f6a8afca3df7459c1c3e284bce167b6cd71c5143aa75943c6d3de8b76dd1a7357f9916a2c",
          "sha256": "a9cb0dddec1312c1cc6bc6a1762ad880f0e8b2a82ea2243b91abf2ac9debb86b",
          "sha1": "a9384de38fc00751084446ba014a0c4962240244",
          "md5": "ebfcdfe96624e5a3de3d0d6522c8593a"
        }
      ]
    }
  ]
}
