{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.1.jar",
          "url": "spring-context-support-6.2.1.jar",
          "size": 174621,
          "sha512": "81309bd1390110914fbc60cd8172febbfcbe556de6aea3e06e6821e1f084d1672ca120eaf0a42f420250d22d8537785e4f2fd164f130ff3bc536c70fe51242da",
          "sha256": "44f1d647ca6cc85432afa3b2eee0402bb4215f83dd2fbed7e76ced5ae5f6fb49",
          "sha1": "455eb5dc0c675dc49044c1518763f4c0323a5860",
          "md5": "8eb9f94f2d5b4bd4f9155660d6ab05af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.1.jar",
          "url": "spring-context-support-6.2.1.jar",
          "size": 174621,
          "sha512": "81309bd1390110914fbc60cd8172febbfcbe556de6aea3e06e6821e1f084d1672ca120eaf0a42f420250d22d8537785e4f2fd164f130ff3bc536c70fe51242da",
          "sha256": "44f1d647ca6cc85432afa3b2eee0402bb4215f83dd2fbed7e76ced5ae5f6fb49",
          "sha1": "455eb5dc0c675dc49044c1518763f4c0323a5860",
          "md5": "8eb9f94f2d5b4bd4f9155660d6ab05af"
        }
      ]
    }
  ]
}
