spring.application.name=demo_project_spring_boot

server.port=8088
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Saveun2032
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.mapper.accept-case-insensitive-enums=true

spring.security.user.name=Saveun
spring.security.user.password=Saveun2032

cloudinary.cloudName=denxb3y4a
cloudinary.apiKey=836246288911529
cloudinary.apiSecret=Ln8TD2E2x6iRxil-8-PYde3fcOA

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true