{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.2.jar",
          "url": "spring-security-crypto-6.4.2.jar",
          "size": 100693,
          "sha512": "65ac84bf7ee1b284ee749b36f61001b7bb05af838e9a118b59e465a015601a1641daaecc5ed02b180bbf09a7a887d888408ec944ab059e4f1357508d0b1623c2",
          "sha256": "00026ef0a248a208920c653abb6b6bfd0c896349dcdc6dda38af8776921d999c",
          "sha1": "a4d5bf27ca449200fc39e07de6ae016eb1ad21da",
          "md5": "be30b5edf5c7e976e3361f1af8a6e069"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.2.jar",
          "url": "spring-security-crypto-6.4.2.jar",
          "size": 100693,
          "sha512": "65ac84bf7ee1b284ee749b36f61001b7bb05af838e9a118b59e465a015601a1641daaecc5ed02b180bbf09a7a887d888408ec944ab059e4f1357508d0b1623c2",
          "sha256": "00026ef0a248a208920c653abb6b6bfd0c896349dcdc6dda38af8776921d999c",
          "sha1": "a4d5bf27ca449200fc39e07de6ae016eb1ad21da",
          "md5": "be30b5edf5c7e976e3361f1af8a6e069"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.2-javadoc.jar",
          "url": "spring-security-crypto-6.4.2-javadoc.jar",
          "size": 241590,
          "sha512": "61811fab594a24c19d39e60b349494819047b9aea5b7ac6ace5b26960c2e47066e48975c81d00e3ad3fa0c99cf2c7e804bc1b260e9723fb4dd8107fbb92ed3a9",
          "sha256": "312cd3366afd48623bcafb7655e87ca21e20daf8cd95448a951dbcaa8e89c77a",
          "sha1": "b92e5970e36edc44ffb1e46f8e08b79f643a4827",
          "md5": "9c975bf8ca1c5fae00ee179bbb19a58c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.2-sources.jar",
          "url": "spring-security-crypto-6.4.2-sources.jar",
          "size": 86696,
          "sha512": "dddaf7599b40958eabcc9109c8da7d77fda0897ca818d73e3a796180fadfdd40bf3f5a67bcab1284b4ccff694dc166f9d3be6cd42ff76fe4620506c44c9d6139",
          "sha256": "f15d7eb918996a25af3a61fb1e450d10ce30c4857f54658f6183adebb2ab2841",
          "sha1": "6c20311510a09e594d9b28ac492699a7dffa02fe",
          "md5": "1f3e1ad11940177f8b9962061d479be3"
        }
      ]
    }
  ]
}
