{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.1.jar",
          "url": "spring-boot-starter-security-3.4.1.jar",
          "size": 4741,
          "sha512": "442a0d180cfc8fe987172cbd6b732b1efd7881f81ff38d4fb3103a34f2a4ed9e4d0d9bcb5837228f1883abc007e9c7b63e36032667dbb9b64806317fe3efa07b",
          "sha256": "12a88f1f25949f88d13328f7960d4b42a2a71556b8b9d114e85df1d3ccab37c6",
          "sha1": "6a82a9f484d265c73a203d551b614cd8bdde5825",
          "md5": "7f1fdb5543d9b7691e496efdb3b8a9ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.1.jar",
          "url": "spring-boot-starter-security-3.4.1.jar",
          "size": 4741,
          "sha512": "442a0d180cfc8fe987172cbd6b732b1efd7881f81ff38d4fb3103a34f2a4ed9e4d0d9bcb5837228f1883abc007e9c7b63e36032667dbb9b64806317fe3efa07b",
          "sha256": "12a88f1f25949f88d13328f7960d4b42a2a71556b8b9d114e85df1d3ccab37c6",
          "sha1": "6a82a9f484d265c73a203d551b614cd8bdde5825",
          "md5": "7f1fdb5543d9b7691e496efdb3b8a9ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-security-3.4.1-javadoc.jar",
          "size": 4741,
          "sha512": "442a0d180cfc8fe987172cbd6b732b1efd7881f81ff38d4fb3103a34f2a4ed9e4d0d9bcb5837228f1883abc007e9c7b63e36032667dbb9b64806317fe3efa07b",
          "sha256": "12a88f1f25949f88d13328f7960d4b42a2a71556b8b9d114e85df1d3ccab37c6",
          "sha1": "6a82a9f484d265c73a203d551b614cd8bdde5825",
          "md5": "7f1fdb5543d9b7691e496efdb3b8a9ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.1-sources.jar",
          "url": "spring-boot-starter-security-3.4.1-sources.jar",
          "size": 4741,
          "sha512": "442a0d180cfc8fe987172cbd6b732b1efd7881f81ff38d4fb3103a34f2a4ed9e4d0d9bcb5837228f1883abc007e9c7b63e36032667dbb9b64806317fe3efa07b",
          "sha256": "12a88f1f25949f88d13328f7960d4b42a2a71556b8b9d114e85df1d3ccab37c6",
          "sha1": "6a82a9f484d265c73a203d551b614cd8bdde5825",
          "md5": "7f1fdb5543d9b7691e496efdb3b8a9ac"
        }
      ]
    }
  ]
}
