{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.2.1.jar",
          "url": "spring-context-6.2.1.jar",
          "size": 1350116,
          "sha512": "1c5cca27dd892ce641f0600ec1cf9c41865f7b33794da86232fb1f35c334cd33ab0e36de0c62824073b3f06b60e72cd5819ec26f15f9d585c1ccfee03c2f5fc3",
          "sha256": "226617237451b420f5742517d1aaa27fb20bb3dbe23db6fb5ea1570bf97ce162",
          "sha1": "f56c7431b03860bfdb016e68f484c5c35531ef2e",
          "md5": "6c650372cd5aef72f5cd4eea1194ef60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.2.1.jar",
          "url": "spring-context-6.2.1.jar",
          "size": 1350116,
          "sha512": "1c5cca27dd892ce641f0600ec1cf9c41865f7b33794da86232fb1f35c334cd33ab0e36de0c62824073b3f06b60e72cd5819ec26f15f9d585c1ccfee03c2f5fc3",
          "sha256": "226617237451b420f5742517d1aaa27fb20bb3dbe23db6fb5ea1570bf97ce162",
          "sha1": "f56c7431b03860bfdb016e68f484c5c35531ef2e",
          "md5": "6c650372cd5aef72f5cd4eea1194ef60"
        }
      ]
    }
  ]
}
