{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-oauth2-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.4.1.jar",
          "url": "spring-boot-starter-oauth2-client-3.4.1.jar",
          "size": 4779,
          "sha512": "690c762b87d28540a40a9fa9367bf6193be5bd202fa3073ff7147e3a22aac06f1f7090778aefa0055d26557d7a490e0d0cd7991fe106ccbc413ed9415cf8a316",
          "sha256": "23cf28bb1083598faab660a4b4d9c20b3cbb88394d34fa83b641d1747478bb00",
          "sha1": "9d39fbd91d9231bf0c9d3259e5152b9bda733f1a",
          "md5": "29c978e95fd452e6bd75624b0ddce80c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.4.1.jar",
          "url": "spring-boot-starter-oauth2-client-3.4.1.jar",
          "size": 4779,
          "sha512": "690c762b87d28540a40a9fa9367bf6193be5bd202fa3073ff7147e3a22aac06f1f7090778aefa0055d26557d7a490e0d0cd7991fe106ccbc413ed9415cf8a316",
          "sha256": "23cf28bb1083598faab660a4b4d9c20b3cbb88394d34fa83b641d1747478bb00",
          "sha1": "9d39fbd91d9231bf0c9d3259e5152b9bda733f1a",
          "md5": "29c978e95fd452e6bd75624b0ddce80c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-oauth2-client-3.4.1-javadoc.jar",
          "size": 4779,
          "sha512": "690c762b87d28540a40a9fa9367bf6193be5bd202fa3073ff7147e3a22aac06f1f7090778aefa0055d26557d7a490e0d0cd7991fe106ccbc413ed9415cf8a316",
          "sha256": "23cf28bb1083598faab660a4b4d9c20b3cbb88394d34fa83b641d1747478bb00",
          "sha1": "9d39fbd91d9231bf0c9d3259e5152b9bda733f1a",
          "md5": "29c978e95fd452e6bd75624b0ddce80c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.4.1-sources.jar",
          "url": "spring-boot-starter-oauth2-client-3.4.1-sources.jar",
          "size": 4779,
          "sha512": "690c762b87d28540a40a9fa9367bf6193be5bd202fa3073ff7147e3a22aac06f1f7090778aefa0055d26557d7a490e0d0cd7991fe106ccbc413ed9415cf8a316",
          "sha256": "23cf28bb1083598faab660a4b4d9c20b3cbb88394d34fa83b641d1747478bb00",
          "sha1": "9d39fbd91d9231bf0c9d3259e5152b9bda733f1a",
          "md5": "29c978e95fd452e6bd75624b0ddce80c"
        }
      ]
    }
  ]
}
