{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-cache",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.1.jar",
          "url": "spring-boot-starter-cache-3.4.1.jar",
          "size": 4761,
          "sha512": "57ca71c601c153a65bb3edb54b7dc838ec4e2c06f2e9718b2eec4c18341109a693f846c19a2f20745cab7351ff22b5d6ab4857c5969c3a03104aa97492665b3d",
          "sha256": "6ef5d4e5a6aebf6278cde1d6f3afdd6a6a32ba0a3f9cc61999fbb0c0cff578b1",
          "sha1": "d3e0a357c187de005f3d30f2a43dd6d884a77196",
          "md5": "877c15ed5cc1459637c3649314c1cba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.1.jar",
          "url": "spring-boot-starter-cache-3.4.1.jar",
          "size": 4761,
          "sha512": "57ca71c601c153a65bb3edb54b7dc838ec4e2c06f2e9718b2eec4c18341109a693f846c19a2f20745cab7351ff22b5d6ab4857c5969c3a03104aa97492665b3d",
          "sha256": "6ef5d4e5a6aebf6278cde1d6f3afdd6a6a32ba0a3f9cc61999fbb0c0cff578b1",
          "sha1": "d3e0a357c187de005f3d30f2a43dd6d884a77196",
          "md5": "877c15ed5cc1459637c3649314c1cba9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-cache-3.4.1-javadoc.jar",
          "size": 4761,
          "sha512": "57ca71c601c153a65bb3edb54b7dc838ec4e2c06f2e9718b2eec4c18341109a693f846c19a2f20745cab7351ff22b5d6ab4857c5969c3a03104aa97492665b3d",
          "sha256": "6ef5d4e5a6aebf6278cde1d6f3afdd6a6a32ba0a3f9cc61999fbb0c0cff578b1",
          "sha1": "d3e0a357c187de005f3d30f2a43dd6d884a77196",
          "md5": "877c15ed5cc1459637c3649314c1cba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.1-sources.jar",
          "url": "spring-boot-starter-cache-3.4.1-sources.jar",
          "size": 4761,
          "sha512": "57ca71c601c153a65bb3edb54b7dc838ec4e2c06f2e9718b2eec4c18341109a693f846c19a2f20745cab7351ff22b5d6ab4857c5969c3a03104aa97492665b3d",
          "sha256": "6ef5d4e5a6aebf6278cde1d6f3afdd6a6a32ba0a3f9cc61999fbb0c0cff578b1",
          "sha1": "d3e0a357c187de005f3d30f2a43dd6d884a77196",
          "md5": "877c15ed5cc1459637c3649314c1cba9"
        }
      ]
    }
  ]
}
