{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.1.jar",
          "url": "spring-boot-starter-tomcat-3.4.1.jar",
          "size": 4793,
          "sha512": "b101debf1930b24565e8194cbdfb0027dc67f800eb3468790b916d753fb51e34f413abb975967de56d7eb38f26accf8f7f984d08d2ec3434efc86c360c60f943",
          "sha256": "7b64ce41136c44a3e81b0d49770ca57076173c4cf024421ee58da707a41f024a",
          "sha1": "ac4bb51582c57cfb0d2beb102a76fe1a4d8b8b21",
          "md5": "db03a88193f0ae195d0ffe4ccf9ee534"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.1.jar",
          "url": "spring-boot-starter-tomcat-3.4.1.jar",
          "size": 4793,
          "sha512": "b101debf1930b24565e8194cbdfb0027dc67f800eb3468790b916d753fb51e34f413abb975967de56d7eb38f26accf8f7f984d08d2ec3434efc86c360c60f943",
          "sha256": "7b64ce41136c44a3e81b0d49770ca57076173c4cf024421ee58da707a41f024a",
          "sha1": "ac4bb51582c57cfb0d2beb102a76fe1a4d8b8b21",
          "md5": "db03a88193f0ae195d0ffe4ccf9ee534"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.4.1-javadoc.jar",
          "size": 4793,
          "sha512": "a86512f82ff2c39931af48f82c87b4b9a1a789ec7736a89f91f5a7d37129f44de3950f8c3382769a2ee64a00324d2b39e826c2c09869d362a767865a1773ed04",
          "sha256": "29553b9e4fbe0d3f429c7347d61d2464db8ddd34a8a641d111366de83c4a7dda",
          "sha1": "370ef7e94c0982a752c4ce5eeb39cc3d1a9a511c",
          "md5": "ddaae536b6449241c11db23370f6928d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.1-sources.jar",
          "url": "spring-boot-starter-tomcat-3.4.1-sources.jar",
          "size": 4793,
          "sha512": "a86512f82ff2c39931af48f82c87b4b9a1a789ec7736a89f91f5a7d37129f44de3950f8c3382769a2ee64a00324d2b39e826c2c09869d362a767865a1773ed04",
          "sha256": "29553b9e4fbe0d3f429c7347d61d2464db8ddd34a8a641d111366de83c4a7dda",
          "sha1": "370ef7e94c0982a752c4ce5eeb39cc3d1a9a511c",
          "md5": "ddaae536b6449241c11db23370f6928d"
        }
      ]
    }
  ]
}
