{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.4.2.jar",
          "url": "spring-security-web-6.4.2.jar",
          "size": 993202,
          "sha512": "0c8deb2a704af6acb77cc74af9a1dc809823504c4659665ad68e7fe47290fe9b7b458be3798fcf0a60c8825d7fc99e844f22f2e8ac08b4b85c4311206dd9747a",
          "sha256": "bc625e47c2cbcd55da04a6939d786da789cb270cd06d418c1adecca165e1e0ff",
          "sha1": "733a3bbbdca56225676fb7f4e3f317c2075fc383",
          "md5": "aac3216773e5e76ace30f4c434f0163e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.4.2.jar",
          "url": "spring-security-web-6.4.2.jar",
          "size": 993202,
          "sha512": "0c8deb2a704af6acb77cc74af9a1dc809823504c4659665ad68e7fe47290fe9b7b458be3798fcf0a60c8825d7fc99e844f22f2e8ac08b4b85c4311206dd9747a",
          "sha256": "bc625e47c2cbcd55da04a6939d786da789cb270cd06d418c1adecca165e1e0ff",
          "sha1": "733a3bbbdca56225676fb7f4e3f317c2075fc383",
          "md5": "aac3216773e5e76ace30f4c434f0163e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.4.2-javadoc.jar",
          "url": "spring-security-web-6.4.2-javadoc.jar",
          "size": 2217047,
          "sha512": "39d46ec92340ab8f0d515e61eebade24d2a0ca8098144f940f632ee8fa53d5d6e8046362b35a7c8ddd6c200a67f825fba04ca929d93853a42c382ebc86dcd6bd",
          "sha256": "c8db81f1228d70eca1e6cbbdaa6b6520f58500f3e13c945fc24fcddb95f1b63d",
          "sha1": "10eb37b781bbb46b2676cfd6ca974e80feb56f3d",
          "md5": "fb70991966b87e74d7faba8c7beee52e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.4.2-sources.jar",
          "url": "spring-security-web-6.4.2-sources.jar",
          "size": 824980,
          "sha512": "caa49d1ed0bc32ba1ec8df0ef3c6613c78365d72dbe3397b003de7c60c8748137d068cda04dba2807e83c8f2d9c58656959d9dfdcf5ea10fc32d18fad872d395",
          "sha256": "5ba0b255d3a196fdae48e7566d3852e1aff204b9d3ff3b7fc92515c6b7f9509a",
          "sha1": "272b679431018586536c4fdcb26f64051c72957f",
          "md5": "c7d29567f9dc130330636e14d7f7eee7"
        }
      ]
    }
  ]
}
