{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-core",
    "version": "6.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.4.2.jar",
          "url": "spring-security-oauth2-core-6.4.2.jar",
          "size": 106181,
          "sha512": "f30aefff0e58f22eb4baa19447b3603ccc7a9545f0bba93dd0983d4bf5272614845b7fb3162ed85a5cd2d2e0394f03aeac633eb21c5a91a2d3540a35dc978e40",
          "sha256": "57dc0be23677d1e273b72d368677b739d95e83e8d730b56a0f9cb3d18ffccc41",
          "sha1": "bbf870c11c26edbe8585d2dbc92261a546a5ff60",
          "md5": "94fb9b1182db699c13dd0369872125d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.4.2.jar",
          "url": "spring-security-oauth2-core-6.4.2.jar",
          "size": 106181,
          "sha512": "f30aefff0e58f22eb4baa19447b3603ccc7a9545f0bba93dd0983d4bf5272614845b7fb3162ed85a5cd2d2e0394f03aeac633eb21c5a91a2d3540a35dc978e40",
          "sha256": "57dc0be23677d1e273b72d368677b739d95e83e8d730b56a0f9cb3d18ffccc41",
          "sha1": "bbf870c11c26edbe8585d2dbc92261a546a5ff60",
          "md5": "94fb9b1182db699c13dd0369872125d6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.4.2-javadoc.jar",
          "url": "spring-security-oauth2-core-6.4.2-javadoc.jar",
          "size": 360723,
          "sha512": "bebaf89a4dc6d484bd182810b4697ae657c26683361de6697f169d8e0797285d324cf550e406869d6a6abaf0409ba13890934eb23edd2daa479e1bb43d0af877",
          "sha256": "6b12ccfff90e79b8866d458b85500e94440646398ababa56877b59d03c1424b1",
          "sha1": "50717a2a64b2885102113c506bfa4a856f53e8d5",
          "md5": "d575fcfd9a248cf5e2d50be4a4c0433f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.4.2-sources.jar",
          "url": "spring-security-oauth2-core-6.4.2-sources.jar",
          "size": 100258,
          "sha512": "3ad88a3d6e4f3242680e7067a8f29b23f3ee30a3c5457186cf375b344b219897e28c8ae6ef8bf56f7b971d39649746944b03c6fc5af4cc0a4d4b88f7bedec3d9",
          "sha256": "9e8008ab1170a20e1981abdde38ecd7f2622566611a922ddf085fc1a25d5e38e",
          "sha1": "92572c7a55a5a95b33335f9dafaf309e5730301d",
          "md5": "33865c28cdbc146f18b92585e7ff71fb"
        }
      ]
    }
  ]
}
