{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.1.jar",
          "url": "spring-boot-buildpack-platform-3.4.1.jar",
          "size": 297152,
          "sha512": "013a54b97f82969f81a147eafc003a8c0f686e49041bcac4205c9849574b23754310e4ff007ff618fed73c189f37273f26bf2eebccbee86c7e1bd6934a246fd9",
          "sha256": "ae03e5def7e6ea17af546611861884f92712c0b15105534f9dd1296df620b481",
          "sha1": "4a7eff8483e69c9693720c59525a3d2625301531",
          "md5": "4d178c1621b71493f8f104e7f4b7e12d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.1.jar",
          "url": "spring-boot-buildpack-platform-3.4.1.jar",
          "size": 297152,
          "sha512": "013a54b97f82969f81a147eafc003a8c0f686e49041bcac4205c9849574b23754310e4ff007ff618fed73c189f37273f26bf2eebccbee86c7e1bd6934a246fd9",
          "sha256": "ae03e5def7e6ea17af546611861884f92712c0b15105534f9dd1296df620b481",
          "sha1": "4a7eff8483e69c9693720c59525a3d2625301531",
          "md5": "4d178c1621b71493f8f104e7f4b7e12d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.1-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.4.1-javadoc.jar",
          "size": 427533,
          "sha512": "86d834af9100d5d8f45bb4fb0ceeb6be9606f3e7efd230786ee408e852f15250c141a8448efc39c8ebcf527abe7176f78915c2e4be125b7bd0c0a553c4e4ad8b",
          "sha256": "d0a27b983ce434347ed56d609ecbc0c955e4ad8a2622e15326b0066be9043c40",
          "sha1": "18cbce65b913d4d94959b7860e28aac75391dfd5",
          "md5": "f36ebcb2ee69a30f7644e40f5d04c49f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.1-sources.jar",
          "url": "spring-boot-buildpack-platform-3.4.1-sources.jar",
          "size": 180316,
          "sha512": "1e0e794d72c986a25a222e582b085ebcab10b12a1eb8baafd55b12ef1596674e181b5aa25bfa9be8ce4e83a3359e76d53a5e98f3a5c7b2cc9fb52ca5a5d20ba7",
          "sha256": "62265787d3cd6b4560128a00a9f0f54a2b499f9e1c911375ca0d81f75b670808",
          "sha1": "4dd9a8e825b7352c4fab170d0cab18fe5408a675",
          "md5": "fad74e4b608dc44dd2750337056ac387"
        }
      ]
    }
  ]
}
