{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-jose",
    "version": "6.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.37.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-jose-6.4.2.jar",
          "url": "spring-security-oauth2-jose-6.4.2.jar",
          "size": 101324,
          "sha512": "20aaed3a43365c4467d5bb3c502e91a9886650a5ecc5b6b2f0c6635d17e311250a24bf3c29d0b32774e457ffc09a28c3865f24f7e951294b63be9eb406fd4488",
          "sha256": "c9c0ee9eabd24c8cea09873253d035b1f7e151a661363d94781b44e1e3ffc3e4",
          "sha1": "274482eaffe0f5e7d978be7cbf7dc1817037efa5",
          "md5": "52d8dd3fc55b6b48e1cf604c8e88824f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.37.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-jose-6.4.2.jar",
          "url": "spring-security-oauth2-jose-6.4.2.jar",
          "size": 101324,
          "sha512": "20aaed3a43365c4467d5bb3c502e91a9886650a5ecc5b6b2f0c6635d17e311250a24bf3c29d0b32774e457ffc09a28c3865f24f7e951294b63be9eb406fd4488",
          "sha256": "c9c0ee9eabd24c8cea09873253d035b1f7e151a661363d94781b44e1e3ffc3e4",
          "sha1": "274482eaffe0f5e7d978be7cbf7dc1817037efa5",
          "md5": "52d8dd3fc55b6b48e1cf604c8e88824f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-jose-6.4.2-javadoc.jar",
          "url": "spring-security-oauth2-jose-6.4.2-javadoc.jar",
          "size": 247860,
          "sha512": "74ebca4f3d53202ca028dc7c09b6b5b1913f4aa4a91a75931895adde7aa456da17a39b18ac9d70f0258eaebb5a641b1f7b048893600494f6b6ddbd4e25f1f79e",
          "sha256": "c4553286e4aada71487d61874f3667022b5677fdc48f0e96d179b38bb09efcd8",
          "sha1": "1f6f449c1018cc361f081e6e25ea4240e1095844",
          "md5": "b668feccfb2359607e5e182313eab759"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-jose-6.4.2-sources.jar",
          "url": "spring-security-oauth2-jose-6.4.2-sources.jar",
          "size": 69568,
          "sha512": "407d5ce7363967389cd1d7e4c9346488df0290c3d1b5f9435f281d8c0e7c68cfbd22e87e329dd0050f2d1898c6dcb07ab848c74432c93a8705e592fd041e6065",
          "sha256": "7b2deef7f931143cdaa7fd8daad7ad69655c68346ae7775752931c21e03dc0d4",
          "sha1": "4db00ce14a0ba2e7c07bb305dc350eca7e0df6b4",
          "md5": "85af6f46a0b786d1ceecb90b94e14d06"
        }
      ]
    }
  ]
}
