{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.1.jar",
          "url": "spring-boot-test-autoconfigure-3.4.1.jar",
          "size": 227039,
          "sha512": "26e10d32a2b8250fbd54017ff19a2dc77ae66c4dee6e9f042f7a01976af929ad5564ce14210dd2ce2b9cacc438bad419e87fd61fc13364a1cebee28881cdb105",
          "sha256": "7cb0a84fa16ebfb58362d881a56a704bf33847dd8344b05e4a6ec1286a67f633",
          "sha1": "87ac4bbb73af12298ddf1cd6830121527e6de7c7",
          "md5": "5937ce667658c3853dbbbe5a51438aa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.1.jar",
          "url": "spring-boot-test-autoconfigure-3.4.1.jar",
          "size": 227039,
          "sha512": "26e10d32a2b8250fbd54017ff19a2dc77ae66c4dee6e9f042f7a01976af929ad5564ce14210dd2ce2b9cacc438bad419e87fd61fc13364a1cebee28881cdb105",
          "sha256": "7cb0a84fa16ebfb58362d881a56a704bf33847dd8344b05e4a6ec1286a67f633",
          "sha1": "87ac4bbb73af12298ddf1cd6830121527e6de7c7",
          "md5": "5937ce667658c3853dbbbe5a51438aa7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.1-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.4.1-javadoc.jar",
          "size": 492847,
          "sha512": "3a8568eecfa3d2acba5ead83f3cb0eb6def69e2abc01f383da8bb6565d4224bd0760fd9064b2ffec1a0174fde0c1c0a3c6943e13957ea5c2c5cc0ca4f89f147c",
          "sha256": "e895eb8152ed2d8f92b78eb0424d18c3d1782021e2b5fa98394a2eab49935690",
          "sha1": "4a151e3f3e3607cd30616fa43c6eb546893e7d8a",
          "md5": "d32d19ca8cee30da54677939a8942c92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.1-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.4.1-sources.jar",
          "size": 226660,
          "sha512": "ab8819cdbbc5974aca7e05a3d074b0f06ec3d4c5daabec4ed34c3320f8b565fb6542bce5cb5c64a29a5ef2b0a1f901849d2f4c93b4ee3762a086be314ec57e4f",
          "sha256": "ac5d33db4000337a40aee5978d529a7b9e6fadd094269658c3b3b812089aa1a3",
          "sha1": "50ef50ff290223703e712697073db4baec3c7238",
          "md5": "8dcbb87e53099c6a6c2909d79ccbbd95"
        }
      ]
    }
  ]
}
