{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.1.jar",
          "url": "spring-boot-starter-validation-3.4.1.jar",
          "size": 4767,
          "sha512": "98bc5b616e0f82c57eb02bb994a95313e21dc4e82c2fc696fa63b111f69ab703dfe722cf885d8e77188b1a44bb0c85081b20eb00466a9ee61938ce1918676782",
          "sha256": "52540ee5996877ee8ce9de1122aa7880f83b35d757ed5b7cb606cedac5fcbfc4",
          "sha1": "7b9baa79c886e362dc14764fc3b0983b607be1f5",
          "md5": "627a8571a290fb49f715a03c99bff426"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.1.jar",
          "url": "spring-boot-starter-validation-3.4.1.jar",
          "size": 4767,
          "sha512": "98bc5b616e0f82c57eb02bb994a95313e21dc4e82c2fc696fa63b111f69ab703dfe722cf885d8e77188b1a44bb0c85081b20eb00466a9ee61938ce1918676782",
          "sha256": "52540ee5996877ee8ce9de1122aa7880f83b35d757ed5b7cb606cedac5fcbfc4",
          "sha1": "7b9baa79c886e362dc14764fc3b0983b607be1f5",
          "md5": "627a8571a290fb49f715a03c99bff426"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-validation-3.4.1-javadoc.jar",
          "size": 4767,
          "sha512": "81d31e46ac5e7fa985cc536c85ba11cd9fc4fe163d637e2f2641c422acb585636d9530536f54b57b6ac6840f13d2de25d9e0d3f8af7aa1293906fe937c84bc0f",
          "sha256": "d7aef30b10d8268e9340d40f5fdf86580eb6a240dcf3f183bf15259f75e02882",
          "sha1": "e06e306666e902b12f4a507a86d88269fed81445",
          "md5": "f49caadfa47c5ad886d1b361f445d18a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.1-sources.jar",
          "url": "spring-boot-starter-validation-3.4.1-sources.jar",
          "size": 4767,
          "sha512": "81d31e46ac5e7fa985cc536c85ba11cd9fc4fe163d637e2f2641c422acb585636d9530536f54b57b6ac6840f13d2de25d9e0d3f8af7aa1293906fe937c84bc0f",
          "sha256": "d7aef30b10d8268e9340d40f5fdf86580eb6a240dcf3f183bf15259f75e02882",
          "sha1": "e06e306666e902b12f4a507a86d88269fed81445",
          "md5": "f49caadfa47c5ad886d1b361f445d18a"
        }
      ]
    }
  ]
}
