{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.1.jar",
          "url": "spring-boot-3.4.1.jar",
          "size": 1761976,
          "sha512": "06b0a25cb5b5e51e0234d7728e49a9172f077f572ff746e08ce7948c4bb4929129622094031d7d00956af4b11565e4aae324ea2af98ecdd039974d281ac7cefe",
          "sha256": "3dffc999ac8eee6b51e8eb9a73c9f29f2a28b7f0f359d45b89aea486268190fa",
          "sha1": "5fb9890a5eb7c4e86c8f5c0f6960b79240daf3d5",
          "md5": "4f7d4f6624312c1ae78bb8a1dd208c80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.1.jar",
          "url": "spring-boot-3.4.1.jar",
          "size": 1761976,
          "sha512": "06b0a25cb5b5e51e0234d7728e49a9172f077f572ff746e08ce7948c4bb4929129622094031d7d00956af4b11565e4aae324ea2af98ecdd039974d281ac7cefe",
          "sha256": "3dffc999ac8eee6b51e8eb9a73c9f29f2a28b7f0f359d45b89aea486268190fa",
          "sha1": "5fb9890a5eb7c4e86c8f5c0f6960b79240daf3d5",
          "md5": "4f7d4f6624312c1ae78bb8a1dd208c80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.1-javadoc.jar",
          "url": "spring-boot-3.4.1-javadoc.jar",
          "size": 2464500,
          "sha512": "25d6a6e1808dfa9f5bb625c81e8d9a8b6247976eaa11233a53aa8ce3f055b066fc9f35e26bfd2fe67f0b6ccf872a48ebaedcea368fe7ecdf88c7c9fa68d599e4",
          "sha256": "b171f9f76cf846b818848b194b16b79bba104d0ef8c4f27e290c33f14ef3ab06",
          "sha1": "8055402e32cd31f538d2dbf6db96831e530a98ca",
          "md5": "05e7bab4f61bc36eabb6ab076633c350"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.1-sources.jar",
          "url": "spring-boot-3.4.1-sources.jar",
          "size": 1184116,
          "sha512": "c5947aa9bb520cd8446527ef87bc44f092b6956e7241bc694a0cc52e4c85cf950b2c65b939f062919d8f787484944c9bca9e58417c40e8903afcb27d352f3b62",
          "sha256": "66723e1572c252c5ed9afba129797426bd2413f67e26d32cbe82bdb3be4b6064",
          "sha1": "ec3e148557698e072c8f2fdfec30af5bfa0221cb",
          "md5": "0c2ac71de00904edcab0c551541c70c2"
        }
      ]
    }
  ]
}
