{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.1.jar",
          "url": "spring-expression-6.2.1.jar",
          "size": 317546,
          "sha512": "10f3ff52b7d4fbb2081005ca37410570e9a7e62b95a4d988cbd44d993a58b26fa7b04a34df84997bfa11ee66d6bd941cadbd99d5e1281150393af441934f8b9f",
          "sha256": "e4efd330d907a506a4ebc558f5ab2f2320a399527474c95316c16d510c9e222e",
          "sha1": "91fcf6b9501705c31c8337e2713fe823bb512b24",
          "md5": "cba4fb289daba10c26882d49062e3e6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.1.jar",
          "url": "spring-expression-6.2.1.jar",
          "size": 317546,
          "sha512": "10f3ff52b7d4fbb2081005ca37410570e9a7e62b95a4d988cbd44d993a58b26fa7b04a34df84997bfa11ee66d6bd941cadbd99d5e1281150393af441934f8b9f",
          "sha256": "e4efd330d907a506a4ebc558f5ab2f2320a399527474c95316c16d510c9e222e",
          "sha1": "91fcf6b9501705c31c8337e2713fe823bb512b24",
          "md5": "cba4fb289daba10c26882d49062e3e6d"
        }
      ]
    }
  ]
}
