{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.1.jar",
          "url": "spring-oxm-6.2.1.jar",
          "size": 59964,
          "sha512": "851f58a956ad13faccbc238fd5984215cc80869ff8d9071d415f4a3a55441b5d7fae424300ee4979fdd0832ce78159da0858e27396d6c58d172243ebc82fda41",
          "sha256": "1063649697e04c6a7728ed98e409c94742e7479535da66a7e48b0b8037fcdea6",
          "sha1": "5adc025b3f67a1931d0fb938b4fca685178672ac",
          "md5": "6f10588b164c09ea77dfa7fdf29cf1f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.1.jar",
          "url": "spring-oxm-6.2.1.jar",
          "size": 59964,
          "sha512": "851f58a956ad13faccbc238fd5984215cc80869ff8d9071d415f4a3a55441b5d7fae424300ee4979fdd0832ce78159da0858e27396d6c58d172243ebc82fda41",
          "sha256": "1063649697e04c6a7728ed98e409c94742e7479535da66a7e48b0b8037fcdea6",
          "sha1": "5adc025b3f67a1931d0fb938b4fca685178672ac",
          "md5": "6f10588b164c09ea77dfa7fdf29cf1f8"
        }
      ]
    }
  ]
}
