{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.1.jar",
          "url": "spring-boot-starter-jdbc-3.4.1.jar",
          "size": 4769,
          "sha512": "d85758cab2a7a29a77acc961ef33ed7b90e99b4f4cca86d5863f722a303fdf672d83a3f63854a8dd53045331172f1515ca27522b1bee30028273de0b3e0908ac",
          "sha256": "5d10a74f37da0cb07c0c737af84e53e1cda06e40666e9d3e70bd7568b690b676",
          "sha1": "307db83ee5f33fe810565cf980f73747b8f8f43b",
          "md5": "c747052392652b508301a9ad3a1d7a57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.1.jar",
          "url": "spring-boot-starter-jdbc-3.4.1.jar",
          "size": 4769,
          "sha512": "d85758cab2a7a29a77acc961ef33ed7b90e99b4f4cca86d5863f722a303fdf672d83a3f63854a8dd53045331172f1515ca27522b1bee30028273de0b3e0908ac",
          "sha256": "5d10a74f37da0cb07c0c737af84e53e1cda06e40666e9d3e70bd7568b690b676",
          "sha1": "307db83ee5f33fe810565cf980f73747b8f8f43b",
          "md5": "c747052392652b508301a9ad3a1d7a57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-jdbc-3.4.1-javadoc.jar",
          "size": 4769,
          "sha512": "cdc1c19378f3705a583aaa5b6fb456a1bc52613a90d7cb4b47e78ab5e383694c1f3133071eea3d54fda331aa85ec08bed03a9574dbb33d3ab2679390331a2de7",
          "sha256": "97b2fa1cb96f54d080accab8afd64b73a04647f0830485a52acf6a7447248288",
          "sha1": "37fb7886d98a26e9994a7071588bdbd70b371b9f",
          "md5": "f2204cd9c2d7a8b5bdbcdca43a32ce87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.1-sources.jar",
          "url": "spring-boot-starter-jdbc-3.4.1-sources.jar",
          "size": 4769,
          "sha512": "cdc1c19378f3705a583aaa5b6fb456a1bc52613a90d7cb4b47e78ab5e383694c1f3133071eea3d54fda331aa85ec08bed03a9574dbb33d3ab2679390331a2de7",
          "sha256": "97b2fa1cb96f54d080accab8afd64b73a04647f0830485a52acf6a7447248288",
          "sha1": "37fb7886d98a26e9994a7071588bdbd70b371b9f",
          "md5": "f2204cd9c2d7a8b5bdbcdca43a32ce87"
        }
      ]
    }
  ]
}
