{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.1.jar",
          "url": "spring-webmvc-6.2.1.jar",
          "size": 1087040,
          "sha512": "bf57a1d95c8cda46bdb00969f92199207bbb6ce506f5d4a7bf6c3ccbbb918276ca2f39daf125c1a11277748eaa93909cbc7f3891c6cfaf974b2b5798c1e67c31",
          "sha256": "42ba27630eb6acb1f2e236ced1f5679eed6037277b06986d7e2cf009537757be",
          "sha1": "44bdf7e5641d44044ac52d7bb5c1fc46004e7754",
          "md5": "44c1d4bf31b0c81eab2ba9e5d27d80f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.1.jar",
          "url": "spring-webmvc-6.2.1.jar",
          "size": 1087040,
          "sha512": "bf57a1d95c8cda46bdb00969f92199207bbb6ce506f5d4a7bf6c3ccbbb918276ca2f39daf125c1a11277748eaa93909cbc7f3891c6cfaf974b2b5798c1e67c31",
          "sha256": "42ba27630eb6acb1f2e236ced1f5679eed6037277b06986d7e2cf009537757be",
          "sha1": "44bdf7e5641d44044ac52d7bb5c1fc46004e7754",
          "md5": "44c1d4bf31b0c81eab2ba9e5d27d80f3"
        }
      ]
    }
  ]
}
